@startuml build_rescue_mission_flow_chart

start

  :開始日時、開始場所、被災地を受け取る;
  :タスクの一覧を作成;
  :被災地への移動タスクを作成;
  :被災地への移動タスクをタスクの一覧に追加;

  :被災地への着陸可能日時を取得;

  :救助タスクを作成;

  if (被災地の移動タスクの終了日時と救助タスクの開始日時に差がある) then (はい)
    :被災地での待機タスクを作成;
    :被災地での待機タスクをタスクの一覧に追加;
  endif

  :救助タスクをタスクの一覧に追加;

  :基地の一覧を取得;
  :降機タスク一覧を作成;
  repeat
    :被災地から基地への移動タスクを作成;
    :基地への着陸可能日時を取得;
    :降機タスクを作成;
    :降機タスク一覧に降機タスクを追加;
  repeat while(基地がある)
  :降機タスク一覧から最も早く終る降機タスクを取得;
  :最も早く終る降機タスクから降機基地を決定;

  :降機基地への移動タスクを作成;
  :降機基地への着陸可能日時を取得;
  :降機タスクを作成;

  if (降機基地の移動タスクの終了日時と降機タスクの開始日時に差がある) then (はい)
    :降機基地での待機タスクの作成;
    :降機基地での待機タスクをタスクの一覧に追加;
  endif

  :給油可能基地の一覧を取得;
  :給油タスクの一覧を作成;
  repeat
    :降機基地から給油基地への移動タスクを作成;
    :給油基地への着陸可能日時を取得;
    :給油タスクを作成;
    :給油タスク一覧に給油タスクを追加;
  repeat while(基地がある)
  :給油タスクの一覧から最も早く終る給油タスクを取得;
  :最も早く終る給油タスクから給油基地を決定;

  :給油基地への移動タスクを作成;
  :給油基地への着陸可能日時を取得;
  :給油タスクを作成;

  if (給油基地の移動タスクの終了日時と給油タスクの開始日時に差がある) then (はい)
    :給油基地での待機タスクの作成;
    :給油基地での待機タスクをタスクの一覧に追加;
  endif

  :タスク一覧からミッションを作成;
end

@enduml
