@startuml build_free_optimal_rescue_mission_flow_chart

start
:対象となる被災地の一覧(a)取得;
repeat
  :被災地の一覧(a)を被災地の一覧(b)とする;
  if (救助率を加味する)
    :救助率が最も低い被災地の一覧(b)を処理の対象とする;
  endif
  :被災地の一覧(b)の被災地から自身の救助ミッション一覧(c)を作成する;
  :ミッション一覧(c)中から最も早く終るミッション(d)を選ぶ;
  :ミッション(d)の被災地(e)を選ぶ;
  :被災地(e)とすべてのヘリコプターから救助ミッションの一覧(f)を作成させる;
  :ミッションの一覧(f)から最も早く終るミッション(g)を選ぶ;
  if (ミッション(g)の実行者が自身である)
    :ミッション(g)を自身の最適なミッション(h)とする;
    break;
  endif
  :被災地の一覧(a)から被災地(e)取り除く;
repeat while(被災地の一覧(a)に被災地が在る)
if (ミッション(c)が存在する)
  :ミッションCを返す;
else
  :空を返す;
endif

stop

@enduml
