@startuml build_free_tasks_flow_chart

start
:すべてのミッションの切り替わり日時を取得;
repeat
  :直前の切り替わり日時;
  if (直前の切り替わり日時がある) then (はい)
    :直前の切り替わり日時の\nミッション数を取得;
    if (直前の切り替わり日時のミッション数が\n平行可能ミッション数未満である) then(はい)
      :ミッション作成可能時間として登録;
      :直前の空き時間を取得;
      if (直前の空き時間の終了日時と\n作成した空き時間の開始日時が同じ) then (はい)
        :２つの空き時間を合わせて\n空き時間として登録する;
      endif
    endif
  endif
repeat while (切り替わり日時がある)
stop
@enduml