@startuml build-return-base-mission-flow-chart

start

:開始日時、開始場所、帰還基地を受け取る;
:タスクの一覧を作成する;

:帰還基地への移動タスクを作成する;
:タスクの一覧に帰還基地への移動タスクを追加する;

:帰還基地への着陸可能日時を取得;
:滞在タスクを作成;

if(帰還基地への移動タスクの終了日時と滞在タスクの開始日時が異なる) then (はい)
  :帰還基地での待機タスクを作成;
  :タスク一覧に帰還基地での待機タスクを追加;
endif

:滞在タスクをタスク一覧に追加;
:タスク一覧からミッションを作成;

stop

@enduml
